import {
	CloudDownloadOutlined,
	ImportOutlined,
	PoweroffOutlined,
	UserSwitchOutlined,
} from '@ant-design/icons';
import React from 'react';

export const umaMenu = [
	{
		label: '启动游戏',
		key: 'START_GAME',
		icon: <PoweroffOutlined />,
	},
	{
		label: '更换马娘',
		key: 'CHANGE_UMAMUSUME',
		popupOffset: [-2, 0],
		popupClassName: 'umamusumesCanChoose',
		icon: <UserSwitchOutlined />,
		children: [
			// NOTE: 这里注释掉的马娘都是我还没抽到的QWQ, 没法录音
			{ key: '特别周', label: '特别周' },
			{ key: '泳装特别周', label: '泳装特别周' },
			{ key: '无声铃鹿', label: '无声铃鹿' },
			{ key: '东海帝王', label: '东海帝王' },
			{ key: '礼装东海帝王', label: '礼装东海帝王' },
			{ key: '目白麦昆', label: '目白麦昆' },
			{ key: '礼装目白麦昆', label: '礼装目白麦昆' },
			// { key: '鲁道夫象征', label: '鲁道夫象征' },
			// { key: '和服鲁道夫象征', label: '和服鲁道夫象征' },
			{ key: '丸善斯基', label: '丸善斯基' },
			{ key: '泳装丸善斯基', label: '泳装丸善斯基' },
			{ key: '小栗帽', label: '小栗帽' },
			{ key: '圣诞小栗帽', label: '圣诞小栗帽' },
			{ key: '大树快车', label: '大树快车' },
			{ key: '米浴', label: '米浴' },
			{ key: '万圣节米浴', label: '万圣节米浴' },
			{ key: '竹正歌剧王', label: '竹正歌剧王' },
			{ key: '春节竹正歌剧王', label: '春节竹正歌剧王' },
			// { key: '美浦波旁', label: '美浦波旁' },
			// { key: '情人节美浦波旁', label: '情人节美浦波旁' },
			{ key: '琵琶晨光', label: '琵琶晨光' },
			{ key: '圣诞琵琶晨光', label: '圣诞琵琶晨光' },
			{ key: '真机伶', label: '真机伶' },
			// { key: '成田大进', label: '成田大进' },
			{ key: '醒目飞鹰', label: '醒目飞鹰' },
			{ key: '成田白仁', label: '成田白仁' },
			{ key: '空中欢歌', label: '空中欢歌' },
			{ key: '婚纱空中欢歌', label: '婚纱空中欢歌' },
			{ key: '摩耶重炮', label: '摩耶重炮' },
			{ key: '婚纱摩耶重炮', label: '婚纱摩耶重炮' },
			// { key: '星云天空', label: '星云天空' },
			// { key: '礼装星云天空', label: '礼装星云天空' },
			// { key: '菱亚马逊', label: '菱亚马逊' },
			{ key: '草上飞', label: '草上飞' },
			{ key: '治愈师草上飞', label: '治愈师草上飞' },
			{ key: '神鹰', label: '神鹰' },
			{ key: '格斗家神鹰', label: '格斗家神鹰' },
			// { key: '富士奇迹', label: '富士奇迹' },
			// { key: '礼装富士奇迹', label: '礼装富士奇迹' },
			{ key: '黄金城市', label: '黄金城市' },
			{ key: '和服黄金城市', label: '和服黄金城市' },
			// { key: '名将怒涛', label: '名将怒涛' },
			{ key: '荣进闪耀', label: '荣进闪耀' },
			{ key: '情人节荣进闪耀', label: '情人节荣进闪耀' },
			{ key: '待兼福来', label: '待兼福来' },
			{ key: '礼装待兼福来', label: '礼装待兼福来' },
			{ key: '菱曙', label: '菱曙' },
			// { key: '爱丽数码', label: '爱丽数码' },
			{ key: '超级小海湾', label: '超级小海湾' },
			{ key: '万圣节超级小海湾', label: '万圣节超级小海湾' },
			// { key: '川上公主', label: '川上公主' },
			{ key: '曼城茶座', label: '曼城茶座' },
			{ key: '东瀛佐敦', label: '东瀛佐敦' },
			// { key: '目白多伯', label: '目白多伯' },
			// { key: '美妙姿势', label: '美妙姿势' },
			// { key: '玉藻十字', label: '玉藻十字' },
			{ key: '春乌拉拉', label: '春乌拉拉' },
			{ key: '春节春乌拉拉', label: '春节春乌拉拉' },
			{ key: '樱花千代王', label: '樱花千代王' },
			// { key: '目白阿尔丹', label: '目白阿尔丹' },
			// { key: '爱慕织姬', label: '爱慕织姬' },
			{ key: '北部玄驹', label: '北部玄驹' },
			// { key: '里见光钻', label: '里见光钻' },
			// { key: '目白光明', label: '目白光明' },
			// { key: '西野花', label: '西野花' },
			// { key: '八重无敌', label: '八重无敌' },
			{ key: '大和赤骥', label: '大和赤骥' },
			{ key: '黄金船', label: '黄金船' },
			{ key: '伏特加', label: '伏特加' },
			{ key: '待兼诗歌剧', label: '待兼诗歌剧' },
			{ key: '目白赖恩', label: '目白赖恩' },
			{ key: '胜利奖券', label: '胜利奖券' },
			{ key: '爱丽速子', label: '爱丽速子' },
			{ key: '樱花进王', label: '樱花进王' },
			{ key: '优秀素质', label: '优秀素质' },
			{ key: '啦啦队优秀素质', label: '啦啦队优秀素质' },
			{ key: '帝王光辉', label: '帝王光辉' },
			{ key: '应援团帝王光辉', label: '应援团帝王光辉' },
		],
	},
	{
		label: '检查更新',
		key: 'CHECK_FOR_UPDATE',
		icon: <CloudDownloadOutlined />,
	},
	{
		label: '退出应用',
		key: 'QUIT',
		icon: <ImportOutlined />,
	},
];
