export const umaNameToUmaCode = function (umaName: string) {
	switch (umaName) {
		case '特别周':
		case '泳装特别周':
			return 'SpecialWeek';
		case '无声铃鹿':
			return 'SilenceSuzuka';
		case '东海帝王':
		case '礼装东海帝王':
			return 'TokaiTeio';
		case '目白麦昆':
		case '礼装目白麦昆':
			return 'MejiroMcQueen';
		case '鲁道夫象征':
		case '和服鲁道夫象征':
			return 'SymboliRudolf';
		case '小栗帽':
		case '圣诞小栗帽':
			return 'OguriCap';
		case '大树快车':
			return 'TaikiShuttle';
		case '米浴':
		case '万圣节米浴':
			return 'RiceShower';
		case '竹正歌剧王':
		case '春节竹正歌剧王':
			return 'T.M.OperaO';
		case '美浦波旁':
		case '情人节美浦波旁':
			return 'MihonoBourbon';
		case '琵琶晨光':
		case '圣诞琵琶晨光':
			return 'BiwaHayahide';
		case '丸善斯基':
		case '泳装丸善斯基':
			return 'MaruZensky';
		case '真机伶':
			return 'CurrenChan';
		case '成田大进':
			return 'NaritaTaishin';
		case '醒目飞鹰':
			return 'SmartFalcon';
		case '成田白仁':
			return 'NaritaBrian';
		case '空中欢歌':
		case '婚纱空中欢歌':
			return 'AirGroove';
		case '摩耶重炮':
		case '婚纱摩耶重炮':
			return 'MayanoTopGun';
		case '星云天空':
		case '礼装星云天空':
			return 'SeiunSky';
		case '菱亚马逊':
			return 'HishiAmazon';
		case '草上飞':
		case '治愈师草上飞':
			return 'GrassWonder';
		case '神鹰':
		case '格斗家神鹰':
			return 'ElCondorPasa';
		case '富士奇迹':
		case '礼装富士奇迹':
			return 'FujiKiseki';
		case '黄金城市':
		case '和服黄金城市':
			return 'GoldCity';
		case '名将怒涛':
			return 'MeishoDoto';
		case '荣进闪耀':
		case '情人节荣进闪耀':
			return 'EishinFlash';
		case '待兼福来':
		case '礼装待兼福来':
			return 'Matikanefukukitaru';
		case '菱曙':
			return 'HishiAkebono';
		case '爱丽数码':
			return 'AgnesDigital';
		case '超级小海湾':
		case '万圣节超级小海湾':
			return 'SuperCreek';
		case '川上公主':
			return 'KawakamiPrincess';
		case '曼城茶座':
			return 'ManhattanCafe';
		case '东瀛佐敦':
			return 'TosenJordan';
		case '目白多伯':
			return 'MejiroDober';
		case '美妙姿势':
			return 'FineMotion';
		case '玉藻十字':
			return 'TamamoCross';
		case '春乌拉拉':
		case '春节春乌拉拉':
			return 'HaruUrara';
		case '樱花千代王':
			return 'SakuraChiyonoO';
		case '目白阿尔丹':
			return 'MejiroArdan';
		case '爱慕织姬':
			return 'AdmireVega';
		case '北部玄驹':
			return 'KitasanBlack';
		case '里见光钻':
			return 'SatonoDiamond';
		case '目白光明':
			return 'MejiroBright';
		case '西野花':
			return 'NishinoFlower';
		case '八重无敌':
			return 'YaenoMuteki';
		case '大和赤骥':
			return 'DaiwaScarlet';
		case '黄金船':
			return 'GoldShip';
		case '伏特加':
			return 'Vodka';
		case '待兼诗歌剧':
			return 'Matikanetannhauser';
		case '目白赖恩':
			return 'MejiroRyan';
		case '胜利奖券':
			return 'WinningTicket';
		case '爱丽速子':
			return 'AgnesTachyon';
		case '樱花进王':
			return 'SakuraBakushinO';
		case '优秀素质':
		case '啦啦队优秀素质':
			return 'NiceNature';
		case '帝王光辉':
		case '应援团帝王光辉':
			return 'KingHalo';
	}
};
